apiVersion: apps/v1
kind: Deployment 
metadata:
  name: new-deployment
spec:
  template:
    metadata:
      name: new-rs-pod
      labels:
        env: non-prod
    spec:
      containers:
        - image: nginx
          name: testing-pod
  replicas: 5
  selector:
    matchLabels:
      env: non-prod